version: '3.9'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3001:3001'
        depends_on:
            - redis
            - mongodb
        env_file:
            - .env
        volumes:
            - ./src:/usr/src/app/src

    redis:
        image: redis:7.2
        volumes:
            - /data

    mongodb:
        image: mongo:6-jammy
        ports:
            - '27017:27017'
        volumes:
            - /data/db
            - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        environment:
            MONGO_INITDB_ROOT_USERNAME: intercom
            MONGO_INITDB_ROOT_PASSWORD: intercom
            MONGO_INITDB_DATABASE: intercom

volumes:
    redisdata:
    mongodata:
